version: '2'

volumes:
    database_data:
        driver: local

services:
    web:
        build: ./docker/web/
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html/

    mysql:
        image: mysql:latest
        expose:
            - ${MYSQL_PORT}
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
